import {
  Abilitiy,
  Attack,
  AttackEffectList,
  Class,
  Creature,
  CreatureEffectList,
  CreatureRewardList,
  Race,
  Skill,
  SkillsList,
  SkillsTree,
  Stat,
  StatsList,
} from "./DTO/BestiaryDTO";

import {
  emptyAbilitiy,
  emptyAttack,
  emptyAttackEffectList,
  emptyClass,
  emptyCreature,
  emptyCreatureEffectList,
  emptyCreatureRewardList,
  emptyRace,
  emptySkill,
  emptySkillsList,
  emptySkillsTree,
  emptyStat,
  emptyStatsList,
} from "./DTO/EmptyCreature";

export {
  Abilitiy,
  Attack,
  AttackEffectList,
  Class,
  Creature,
  CreatureEffectList,
  CreatureRewardList,
  Race,
  Skill,
  SkillsList,
  SkillsTree,
  Stat,
  StatsList,

  emptyAbilitiy,
  emptyAttack,
  emptyAttackEffectList,
  emptyClass,
  emptyCreature,
  emptyCreatureEffectList,
  emptyCreatureRewardList,
  emptyRace,
  emptySkill,
  emptySkillsList,
  emptySkillsTree,
  emptyStat,
  emptyStatsList,
};
